apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app.kubernetes.io/name: snmp-monitoring
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace