apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoriametrics-storage
  namespace: monitoring
  labels:
    app.kubernetes.io/name: victoriametrics
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoriametrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: victoriametrics
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: victoriametrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: victoriametrics
        app.kubernetes.io/component: database
    spec:
      containers:
      - name: victoriametrics
        image: victoriametrics/victoria-metrics:v1.96.0
        ports:
        - containerPort: 8428
          name: http
          protocol: TCP
        args:
        - --storageDataPath=/victoria-metrics-data
        - --httpListenAddr=:8428
        - --retentionPeriod=12
        - --memory.allowedPercent=80
        - --search.maxQueryDuration=30m
        - --search.maxConcurrentRequests=8
        volumeMounts:
        - name: storage
          mountPath: /victoria-metrics-data
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2
            memory: 4Gi
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: victoriametrics-storage

---
apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: victoriametrics
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
  - port: 8428
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: victoriametrics

---
apiVersion: v1
kind: Service
metadata:
  name: victoriametrics-nodeport
  namespace: monitoring
  labels:
    app.kubernetes.io/name: victoriametrics
    app.kubernetes.io/component: service-external
spec:
  type: NodePort
  ports:
  - port: 8428
    targetPort: http
    protocol: TCP
    name: http
    nodePort: 30428
  selector:
    app.kubernetes.io/name: victoriametrics